import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from '@/components/session-provider'
import { auth, BASE_PATH } from '@/lib/auth'
import { twMerge } from 'tailwind-merge'
import { QueryClientWrapper } from '@/components/query-client-wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en" className="dark">
      <body className={twMerge(inter.className, 'bg-black')}>
        <SessionProvider basePath={BASE_PATH} session={session}>
          <QueryClientWrapper>{children}</QueryClientWrapper>
        </SessionProvider>
      </body>
    </html>
  )
}
