import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from '@/components/session-provider'
import { auth, BASE_PATH } from '@/lib/auth'
import { twMerge } from 'tailwind-merge'
import { QueryClientWrapper } from '@/components/query-client-wrapper'
import { Toaster } from '@/components/ui/sonner'
import { ProductsProvider } from '@/contexts/products-context'
import { SuppliersProvider } from '@/contexts/suppliers-context'
import { OrdersProvider } from '@/contexts/orders-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en" className="dark">
      <body className={twMerge(inter.className, 'bg-black')}>
        <SessionProvider basePath={BASE_PATH} session={session}>
          <QueryClientWrapper>
            <SuppliersProvider>
              <OrdersProvider>
                <ProductsProvider>{children}</ProductsProvider>
              </OrdersProvider>
            </SuppliersProvider>
          </QueryClientWrapper>
        </SessionProvider>
        <Toaster richColors />
      </body>
    </html>
  )
}
